// react/exemple/src/components/Input/Input.js
import React from 'react';

class Input extends React.Component {

  state = {
    showStyle: this.props.value
  }

  onChange = (e) => {
    const { changeValue, name, isValid, pattern} = this.props;
    changeValue(e.target.value, name)
    this.setState({showStyle: true})
    let valid = pattern.test(e.target.value)
    isValid(valid, name);
  }

  render() {

    const { showStyle } = this.state;
    const { value, name, pattern, isValid } = this.props;

    let getStyle = () => {
      if (showStyle) {
        return pattern.test(value) ? {background: "green"} : {background: "red"}
      }
    }

    return (
      <div>
        <p>{name}</p>
        <input value={value} onChange={this.onChange} style={getStyle()}/>
      </div>
    )
  }
}

export default Input;

// vue/lavr/app1/src/components/Input.vue
<template>
  <div >
    <p>{{name}}</p>
    <input :value="value" :class="setClass" @input="onInput">
  </div>
</template>

<script>
export default {
  props: {
    name: String,
    value: String,
    pattern: RegExp
  },
  data() {
    return {
      showClass: this.value
    }
  },
  computed: {
    setClass() {
      if (this.showClass) {
        let valid = this.pattern.test(this.value);
         this.$emit("changevalue", {
            value: this.value,
            valid: valid
          })
        return valid ? "ok" : "off";
      }
    }
  },
  methods: {
    onInput(e) {
      this.showClass = true;
      this.$emit("changevalue", {
        value: e.target.value,
        valid: this.pattern.test(e.target.value)
      })
    }
  }
}
</script>

<style scoped lang="scss">

  .ok {
    background: lightgreen;
  }

  .off {
    background: red;
  }

</style>
