// react/vue-react/src/components/Input/Input.js
import React, { Component } from 'react';

import  './Input.scss';
export class Input extends Component {

  state = {
    showClass: this.props.value
  }

  componentDidMount() {
    const {value, pattern, changeValue} = this.props;
    setTimeout(() => {
      changeValue(value, pattern.test(value));
    }, 0);
  }

  changeValue = (e) => {
    let {changeValue, pattern} = this.props;
    let valid = pattern.test(e.target.value);
    changeValue(e.target.value, valid);
    this.setState({showClass: true});
  }

  setClass = () => {
    const {value, pattern, changeValue} = this.props;
    if (this.state.showClass) {
      
      return pattern.test(value) ? "ok" : "off";
    }
  }

  render() {

    const {name, value, pattern} = this.props;

    let classInput = this.setClass();

    return (
      <div>
        <p>{name}</p>
        <input value={value} onChange={this.changeValue} className={classInput} />
      </div>
    );
  }
}

export default Input;

// vue/lavr/app1/src/components/Input.vue
<template>
  <div >
    <p>{{name}}</p>
    <input :value="value" :class="setClass" @input="onInput">
  </div>
</template>

<script>
export default {
  props: {
    name: String,
    value: String,
    pattern: RegExp
  },
  data() {
    return {
      showClass: this.value
    }
  },
  computed: {
    setClass() {
      if (this.showClass) {
        let valid = this.pattern.test(this.value);
         this.$emit("changevalue", {
            value: this.value,
            valid: valid
          })
        return valid ? "ok" : "off";
      }
    }
  },
  methods: {
    onInput(e) {
      this.showClass = true;
      this.$emit("changevalue", {
        value: e.target.value,
        valid: this.pattern.test(e.target.value)
      })
    }
  }
}
</script>

<style scoped lang="scss">

  .ok {
    background: lightgreen;
  }

  .off {
    background: red;
  }

</style>
