// react/master-2/src/components/ErrorIndicator/ErrorIndicator.js
import React from 'react';

import './ErrorIndicator.scss';

const ErrorIndicator = () => {
  return (
    <div className="error-indicator">
      <img src="./death-star.png" alt="error icon"/>
      <span className="boom">BOOM!</span>
      <span>
        something has gone terribly wrong
      </span>
      <span>
        (but we already sent droids to fix it)
      </span>
    </div>
  );
};

export default ErrorIndicator;

// project/StarWars/src/components/ErrorIndicator.vue
<template>
   <div class="error-indicator">
      <img src="../img/death-star.png" alt="error icon"/>
      <span class="boom">BOOM!</span>
      <span>
        something has gone terribly wrong
      </span>
      <span>
        (but we already sent droids to fix it)
      </span>
  </div>
</template>

<script>

export default {
  
}
</script>


<style lang="scss" scoped>

.error-indicator {
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #c78f22;
}

.error-indicator img {
  margin-bottom: 1rem;
}

.error-indicator .boom {
  font-size: 1.7rem;
}
</style>
